### ISSUE TITLE
Contrib

### ISSUE THREAD

**Issue by savez** [goksan/statusnook#10]
hello, if you would like to contribute, are there any rules?

**Comment by goksan** [comment]
Hi @savez, thanks for your question.

The main thing I'd say is that in order to prevent any disappointment I'd encourage discussing any changes in an issue before beginning work intended to be upstreamed.

Did you have a particular contribution in mind?

**Comment by goksan** [comment]
Hi @savez, thanks for your question.

The main thing I'd say is that in order to prevent any disappointment I'd encourage discussing any changes in an issue before beginning work intended to be upstreamed.

Did you have a particular contribution in mind?

**Comment by chw-webops** [comment]
@goksan This is a great app you wrote. Nice and simple, small footprint and fast. I'd love to contribute as well.

**Comment by goksan** [comment]
Thanks again! Feel free to open an issue to discuss a specific contribution should one arise.
