### ISSUE TITLE
Make optional to show Monitors as a public page

### ISSUE THREAD

**Issue by djalmaaraujo** [goksan/statusnook#20]
Thanks for this statusnook project, it's great. We (a group of friends) see more value in displaying the Monitors instead of the Services since we usually more as an internal monitoring tool, and we would like to see the green/red/yellow quickly instead of opening alerts.

Can you make this an option in the admin? If we contribute, would this be acceptable?

Thank you!

**Comment by goksan** [comment]
Hi @djalmaaraujo, thank you for the kind words.

I think I've understood your request and have quickly put something together, here's a screenshot:
![image](https://github.com/user-attachments/assets/18eefb00-1698-46d0-9ecc-f4f8c167c94e)

I've shared my changes on a branch [goksan/monitors-on-index](https://github.com/goksan/statusnook/tree/goksan/monitors-on-index). You're welcome to compile and use this independently if it suits your use case.

If you're keen to contribute this for benefit of other users (no pressure) we'll need at least need:
* an option in the admin (as you've suggested)
* an option in the [text-based config](https://github.com/goksan/statusnook/blob/main/docs/configuration.md)
* there might be other (hopefully) minor bits I haven't thought of

**Comment by djalmaaraujo** [comment]
@goksan Thanks for the fast response. I don't know if the screenshot shows what I meant. Still, I prefer to see the list of monitors instead of services since I can see the red flag if a monitor fails. Still, I will only see a red flag in service if I create an alert, which, in our case, is not so great for us since we don't need to communicate internally with that kind of detail.

The monitoring page + the Slack integration is good enough for us to have visibility + notifications.

**Comment by goksan** [comment]
In the screenshot I've tried to demonstrate that I've swapped services for monitors, you'll see a red flag depending on whether or not a monitor is failing.

The monitor "Testing" is failing.
The monitor "Google" is succeeding.

Let me know if I've still misunderstood you, and what you were expecting to see.

**Comment by djalmaaraujo** [comment]
@goksan Yes, that's the idea, sorry for not picking up the idea faster hehe.

**Comment by djalmaaraujo** [comment]
@goksan Also, I don't see how to set up the project locally to do any development in the README. I would love to see some instructions since I am not a go expert.

**Comment by goksan** [comment]
For development:

* Install Go
* Clone repo
* Run `go build && ./statusnook`

----

For production builds:

I'm assuming you're on macOS due to one of your repos, let me know if this is not the case.

* Run `brew install FiloSottile/musl-cross/musl-cross`, needed for  [go-sqlite3](https://github.com/mattn/go-sqlite3?tab=readme-ov-file#cross-compiling-from-macos).
* Run `./compile.sh` 
* Find the x86 and arm64 Linux builds in the `bin` folder.
