### ISSUE TITLE
Question: How to create other admin users or change a password

### ISSUE THREAD

**Issue by chw-webops** [goksan/statusnook#8]
**I have two questions:**

1. Based on the code + the DB schema it seems like the application can support multiple admin accounts. How do I create new ones?
2. Is it possible to change the password of the admin account created during the set up steps?

**Comment by goksan** [comment]
Hey @chw-webops, thanks for the reminder.

There’s no UI exposed for creating additional admin users, nor for changing the password of the existing admin user.

I will address these as a priority when I have availability, this should be within the next few days.

Let me know if you had any additional concerns regarding these features.

**Comment by goksan** [comment]
Hey @chw-webops, I should be able to release this after the weekend. Let's say by Tuesday.


https://github.com/goksan/statusnook/assets/17437810/b659808b-dde4-4f1c-aa83-beeaa723ce52

**Comment by goksan** [comment]
Hi @chw-webops, thanks again for the reminder.

This has been added, there's a video included here: https://github.com/goksan/statusnook/pull/11

You'll be able to invite new admin users and change their passwords once you upgrade to v0.2.0.

Let me know if you have any additional questions.
